# Generated by Django 6.0 on 2026-01-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metrics',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('profile_edit', 'Profile Edit'), ('note_upload', 'Note Upload'), ('note_delete', 'Note Delete'), ('resource_upload', 'Resource Upload'), ('resource_delete', 'Resource Delete'), ('rating', 'Rating'), ('recommendation', 'Recommendation'), ('group_create', 'Group Create'), ('post_create', 'Post Create'), ('comment_create', 'Comment Create'), ('message', 'Message'), ('chat_clear', 'Chat Clear')], max_length=30),
        ),
    ]
