# Generated by Django 6.0 on 2026-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_delete_metrics_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('search', 'Search'), ('note_download', 'Note Downloaded'), ('resource_download', 'Resource Downloaded'), ('rating', 'Rating Given'), ('recommendation', 'Recommendation Made'), ('group_create', 'Group Created'), ('group_post', 'Group Post'), ('comment', 'Comment Added'), ('message', 'Message Sent')], max_length=50),
        ),
    ]
