# Generated by Django 6.0 on 2026-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_activitylog_options_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('search', 'Search'), ('note_download', 'Note Downloaded'), ('resource_download', 'Resource Downloaded'), ('rating', 'Rating Given'), ('recommendation', 'Recommendation Made'), ('group_create', 'Group Created'), ('group_post', 'Group Post'), ('comment', 'Comment Added'), ('message', 'Message Sent'), ('login', 'User Logged In'), ('logout', 'User Logged Out')], max_length=50),
        ),
    ]
