"""
Django settings for lrhub project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# --- Security ---
SECRET_KEY = 'django-insecure-f3$^okaocj(f=&q_281do-!a&q!9-ri^^7i7xnw8i@!al8g)-p'
DEBUG = True

# ✅ Allow local subdomains for testing
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "admin.localhost",
    "app.localhost",
]

# --- Applications ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts.apps.AccountsConfig',
    'resources.apps.ResourcesConfig',
    'collaboration',
    'analytics.apps.AnalyticsConfig',
]

# --- Middleware ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',   # handles sessions
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.TeacherApprovalMiddleware',
    
]

ROOT_URLCONF = 'lrhub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'lrhub' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lrhub.wsgi.application'

# --- Database ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'arivuverse_db',
        'USER': 'root',
        'PASSWORD': 'ArivuVerse@2026',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # keep default
]
# --- Password validation ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internationalization ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- Static files ---
STATIC_URL = 'static/'
#STATICFILES_DIRS = [BASE_DIR / "static"]   # add for development
# STATIC_ROOT = BASE_DIR / "staticfiles"   # uncomment for production collectstatic

# --- Media files ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- Redirects ---
LOGIN_REDIRECT_URL = '/accounts/role-redirect/'
LOGOUT_REDIRECT_URL = 'home'

# --- Session & CSRF isolation ---
# Each subdomain gets its own cookie, so admin and app sessions don’t clash
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None


EMAIL_BACKEND = 'accounts.backends.NoWrapConsoleEmailBackend' # for testing
PASSWORD_RESET_TIMEOUT = 86400  #(default is 86400 seconds = 1 day)

