# Generated by Django 6.0 on 2026-01-12 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_rating_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentresource',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'note'), name='unique_user_note_rating'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'resource'), name='unique_user_resource_rating'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('user', 'note'), name='unique_user_note_recommendation'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('user', 'resource'), name='unique_user_resource_recommendation'),
        ),
    ]
