# Generated by Django 6.0 on 2026-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentresource',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
