# Generated by Django 6.0 on 2026-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_note_downloads_studentresource_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, choices=[('Computer', 'Computer'), ('Social', 'Social'), ('ML', 'Machine Learning'), ('AI', 'Artificial Intelligence'), ('Science', 'Science'), ('History', 'History'), ('Math', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Economics', 'Economics'), ('Politics', 'Politics'), ('Geography', 'Geography'), ('Philosophy', 'Philosophy'), ('Psychology', 'Psychology'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Medicine', 'Medicine'), ('Law', 'Law'), ('Arts', 'Arts'), ('Literature', 'Literature'), ('Music', 'Music'), ('Sports', 'Sports'), ('Business', 'Business'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentresource',
            name='category',
            field=models.CharField(blank=True, choices=[('Computer', 'Computer'), ('Social', 'Social'), ('ML', 'Machine Learning'), ('AI', 'Artificial Intelligence'), ('Science', 'Science'), ('History', 'History'), ('Math', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Economics', 'Economics'), ('Politics', 'Politics'), ('Geography', 'Geography'), ('Philosophy', 'Philosophy'), ('Psychology', 'Psychology'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Medicine', 'Medicine'), ('Law', 'Law'), ('Arts', 'Arts'), ('Literature', 'Literature'), ('Music', 'Music'), ('Sports', 'Sports'), ('Business', 'Business'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
