# Generated by Django 6.0 on 2026-01-31 17:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_note_category_studentresource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='studentresource',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
